development:
  adapter: any_cable

test:
  adapter: any_cable

production:
  adapter: any_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: coreui_pro_rails_starter_production
